-- MoodTrip anonymous multi-user learning schema
-- Apply once to the connected Supabase project.

create table if not exists public.moodtrip_feedback (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  session_id text not null,
  event_type text not null default 'feedback',
  recommendation_id text,
  rank_position integer,
  mood text not null,
  category text not null,
  place_id text not null,
  place_name text,
  positive boolean,
  model_score real,
  neural_score real,
  distance_km real,
  rating real,
  group_mode boolean not null default false,
  rank_features jsonb not null,
  model_version text not null default 'distilled-nn-v1',
  provider text,
  source text not null default 'moodtrip-web'
);

-- Idempotent upgrades if an older version of the schema already exists.
alter table public.moodtrip_feedback add column if not exists event_type text not null default 'feedback';
alter table public.moodtrip_feedback add column if not exists recommendation_id text;
alter table public.moodtrip_feedback add column if not exists rank_position integer;
alter table public.moodtrip_feedback add column if not exists provider text;
alter table public.moodtrip_feedback alter column positive drop not null;

create index if not exists moodtrip_feedback_mood_idx
  on public.moodtrip_feedback(mood);
create index if not exists moodtrip_feedback_place_idx
  on public.moodtrip_feedback(place_id);
create index if not exists moodtrip_feedback_created_idx
  on public.moodtrip_feedback(created_at desc);
create index if not exists moodtrip_feedback_rec_idx
  on public.moodtrip_feedback(recommendation_id);

create or replace view public.moodtrip_feedback_aggregate as
select
  mood,
  category,
  place_id,
  count(*) filter (where event_type='feedback' and positive is true) as pos,
  count(*) filter (where event_type='feedback' and positive is false) as neg
from public.moodtrip_feedback
group by mood, category, place_id;

alter table public.moodtrip_feedback enable row level security;
revoke all on public.moodtrip_feedback from anon, authenticated;
revoke all on public.moodtrip_feedback_aggregate from anon, authenticated;
