-- MoodTrip anonymous multi-user learning schema
-- Server-side Vercel functions write with the Supabase service role.
-- Browser roles have no direct access to raw feedback.

create table if not exists public.moodtrip_feedback (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  session_id text not null,
  event_type text not null default 'feedback',
  recommendation_id text not null,
  rank_position integer,
  mood text not null,
  category text not null,
  place_id text not null,
  place_name text,
  positive boolean,
  model_score real,
  neural_score real,
  distance_km real,
  rating real,
  group_mode boolean not null default false,
  rank_features jsonb not null,
  model_version text not null default 'distilled-nn-v1',
  provider text,
  source text not null default 'moodtrip-web',
  constraint moodtrip_event_type_check check (event_type in ('impression','feedback')),
  constraint moodtrip_feedback_label_check check (
    (event_type='impression' and positive is null) or
    (event_type='feedback' and positive is not null)
  ),
  constraint moodtrip_rank_position_check check (rank_position is null or rank_position between 1 and 100),
  constraint moodtrip_rating_check check (rating is null or rating between 0 and 5),
  constraint moodtrip_distance_check check (distance_km is null or distance_km between 0 and 1000)
);

alter table public.moodtrip_feedback add column if not exists event_type text not null default 'feedback';
alter table public.moodtrip_feedback add column if not exists recommendation_id text;
alter table public.moodtrip_feedback add column if not exists rank_position integer;
alter table public.moodtrip_feedback add column if not exists provider text;
alter table public.moodtrip_feedback alter column positive drop not null;

-- Backfill legacy rows before enforcing recommendation IDs for future deduplication.
update public.moodtrip_feedback
set recommendation_id='legacy-'||id::text
where recommendation_id is null or recommendation_id='';

alter table public.moodtrip_feedback alter column recommendation_id set not null;

create index if not exists moodtrip_feedback_mood_idx
  on public.moodtrip_feedback(mood);
create index if not exists moodtrip_feedback_place_idx
  on public.moodtrip_feedback(place_id);
create index if not exists moodtrip_feedback_created_idx
  on public.moodtrip_feedback(created_at desc);
create index if not exists moodtrip_feedback_rec_idx
  on public.moodtrip_feedback(recommendation_id);

-- Makes client retries idempotent and prevents duplicate impressions/feedback
-- from inflating the learning signal.
create unique index if not exists moodtrip_feedback_event_unique
  on public.moodtrip_feedback(session_id,recommendation_id,place_id,event_type);

drop view if exists public.moodtrip_feedback_aggregate;
create view public.moodtrip_feedback_aggregate
with (security_invoker = true)
as
select
  mood,
  category,
  place_id,
  count(*) filter (where event_type='feedback' and positive is true) as pos,
  count(*) filter (where event_type='feedback' and positive is false) as neg
from public.moodtrip_feedback
group by mood, category, place_id;

alter table public.moodtrip_feedback enable row level security;

-- Raw interaction data is private. Only the server-side service role can
-- bypass RLS. Public clients use /api/feedback and never receive credentials.
revoke all on public.moodtrip_feedback from anon, authenticated;
revoke all on public.moodtrip_feedback_aggregate from anon, authenticated;
