-- MoodTrip anonymous multi-user learning schema
-- Apply once to the connected Supabase project.

create table if not exists public.moodtrip_feedback (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  session_id text not null,
  mood text not null,
  category text not null,
  place_id text not null,
  place_name text,
  positive boolean not null,
  model_score real,
  neural_score real,
  distance_km real,
  rating real,
  group_mode boolean not null default false,
  rank_features jsonb not null,
  model_version text not null default 'distilled-nn-v1',
  source text not null default 'moodtrip-web'
);

create index if not exists moodtrip_feedback_mood_idx
  on public.moodtrip_feedback(mood);
create index if not exists moodtrip_feedback_place_idx
  on public.moodtrip_feedback(place_id);
create index if not exists moodtrip_feedback_created_idx
  on public.moodtrip_feedback(created_at desc);

create or replace view public.moodtrip_feedback_aggregate as
select
  mood,
  category,
  place_id,
  count(*) filter (where positive) as pos,
  count(*) filter (where not positive) as neg
from public.moodtrip_feedback
group by mood, category, place_id;

alter table public.moodtrip_feedback enable row level security;

-- Browser clients never talk directly to this table.
-- The Vercel Function uses the server-only service-role key.
revoke all on public.moodtrip_feedback from anon, authenticated;
revoke all on public.moodtrip_feedback_aggregate from anon, authenticated;
