import React, {useEffect, useRef} from 'react';
import { createRoot } from 'react-dom/client';
import { Github, ArrowUpRight, Download, Mail, MapPin, Code2, Database, BrainCircuit } from 'lucide-react';
import './styles.css';

const projects = [
  {num:'01', title:'Startup Funding Analytics', repo:'startupfunding01', href:'https://github.com/divbytes-prog/startupfunding01', desc:'Interactive startup analytics work focused on funding patterns, exploration and visual storytelling.', tags:['Data','Analytics','Python']},
  {num:'02', title:'Lawn Tennis', repo:'launtennis', href:'https://github.com/divbytes-prog/launtennis', desc:'A TypeScript project that shows my front-end/product-building side beyond notebooks and dashboards.', tags:['TypeScript','Web','Product']},
  {num:'03', title:'Hearthlog', repo:'hearthlog', href:'https://github.com/divbytes-prog/hearthlog', desc:'Hackathon project built for IIT Bhubaneswar — rapid product development under a competition constraint.', tags:['Hackathon','Build','Prototype']},
  {num:'04', title:'IIT Hackathon', repo:'iit_hackathon', href:'https://github.com/divbytes-prog/iit_hackathon', desc:'JavaScript-based hackathon work: shipping a working idea quickly, collaboratively and iteratively.', tags:['JavaScript','Hackathon','Web']},
];
const stack = [['Languages','Python · C++ · Java · JavaScript · SQL'],['Data / ML','Pandas · NumPy · Matplotlib · Plotly · Scikit-learn'],['Web','React · HTML · CSS · Flask · Streamlit · Node.js'],['Tools','Git · GitHub · Jupyter · VS Code · AWS · Tableau']];
function Shards(){const ref=useRef(null);useEffect(()=>{const el=ref.current;if(!el)return;const move=(e)=>{const r=el.getBoundingClientRect();el.style.setProperty('--mx',`${((e.clientX-r.left)/r.width)*100}%`);el.style.setProperty('--my',`${((e.clientY-r.top)/r.height)*100}%`)};el.addEventListener('pointermove',move);return()=>el.removeEventListener('pointermove',move)},[]);return <div className="shards" ref={ref} aria-hidden="true"><i/><i/><i/><i/><i/><i/><i/><i/><i/><i/><i/><i/></div>}
function App(){return <main>
<nav className="nav shell"><a className="mark" href="#top">DS<span>.</span></a><div className="navlinks"><a href="#work">Work</a><a href="#about">About</a><a href="#stack">Stack</a></div><a className="navcta" href="mailto:24DCS032@lnmiit.ac.in">Let’s talk <ArrowUpRight size={15}/></a></nav>
<section className="hero shell" id="top"><div className="eyebrow"><span className="pulse"/> Available for research & internship opportunities</div><h1>I build at the intersection of <em>data, ML</em> and the web.</h1><p className="heroCopy">I’m Divyansh Singh, a Computer Science student at LNMIIT. I like turning messy data and ambitious ideas into useful, shippable products.</p><div className="heroActions"><a className="primary" href="#work">See selected work <ArrowUpRight size={17}/></a><a className="secondary" href="https://github.com/divbytes-prog" target="_blank" rel="noreferrer"><Download size={16}/> GitHub</a></div><div className="heroMeta"><span><MapPin size={14}/> Jaipur, India</span><span>CS · 2024—2029</span><span>250+ DSA problems</span></div><Shards/></section>
<section className="statement shell" id="about"><p className="kicker">01 / PROFILE</p><div className="statementGrid"><h2>Engineer in training.<br/>Builder by habit.</h2><div><p>I’m pursuing a B.Tech + M.Tech dual degree in Computer Science and Engineering at LNMIIT. My work spans machine learning, analytics, interactive dashboards and modern web development.</p><p>I’m especially interested in projects where the model is only half the job — the other half is making the result understandable, usable and deployable.</p></div></div><div className="metrics"><div><strong>92%</strong><span>Class XII</span></div><div><strong>96</strong><span>JEE Main percentile</span></div><div><strong>250+</strong><span>DSA problems</span></div><div><strong>2×</strong><span>Olympiad gold medalist</span></div></div></section>
<section className="work shell" id="work"><div className="sectionHead"><div><p className="kicker">02 / SELECTED WORK</p><h2>Projects I’ve shipped.</h2></div><a href="https://github.com/divbytes-prog" target="_blank" rel="noreferrer">All repositories <Github size={16}/></a></div><div className="projectList">{projects.map(p=><a className="project" href={p.href} target="_blank" rel="noreferrer" key={p.repo}><span className="pnum">{p.num}</span><div className="projectMain"><div className="projectTitle"><h3>{p.title}</h3><ArrowUpRight size={22}/></div><p>{p.desc}</p><div className="tags">{p.tags.map(t=><span key={t}>{t}</span>)}</div></div><span className="repo">github/{p.repo}</span></a>)}</div></section>
<section className="featured shell"><p className="kicker">03 / RESUME HIGHLIGHTS</p><div className="featureGrid"><article><BrainCircuit/><span>ML SYSTEM</span><h3>Real Estate ML Application</h3><p>Regression modeling, feature engineering, model comparison, analytics and recommendations — deployed with Streamlit and AWS.</p></article><article><Database/><span>DATA PRODUCT</span><h3>India Visualization Dashboard</h3><p>Interactive visualization of 120+ demographic and socioeconomic parameters with Plotly maps and dynamic filtering.</p></article><article><Code2/><span>AI PRODUCT</span><h3>Career Assistant</h3><p>React + TypeScript career guidance platform with personalized roadmaps, salary insights, learning discovery and an AI assistant.</p></article></div></section>
<section className="stack shell" id="stack"><div><p className="kicker">04 / TOOLBOX</p><h2>The tools are secondary.<br/>Shipping is the point.</h2></div><div className="stackList">{stack.map(([a,b])=><div key={a}><span>{a}</span><p>{b}</p></div>)}</div></section>
<section className="contact shell"><p className="kicker">05 / CONTACT</p><h2>Have a problem worth<br/><em>building for?</em></h2><div className="contactRow"><a href="mailto:24DCS032@lnmiit.ac.in"><Mail/> 24DCS032@lnmiit.ac.in</a><a href="https://github.com/divbytes-prog" target="_blank" rel="noreferrer"><Github/> github.com/divbytes-prog</a></div></section>
<footer className="shell"><span>© {new Date().getFullYear()} Divyansh Singh</span><span>Designed with restraint. Built with React.</span><a href="#top">Back to top ↑</a></footer></main>}
createRoot(document.getElementById('root')).render(<App/>);