import React,{useEffect,useState}from'react';import{createRoot}from'react-dom/client';import{SiPython,SiCplusplus,SiJavascript,SiReact,SiNodedotjs,SiFlask,SiPandas,SiNumpy,SiScikitlearn,SiPlotly,SiAmazonwebservices,SiGit,SiMysql}from'react-icons/si';import AeroShards from'./AeroShards';import LogoLoop from'./LogoLoop';import'./styles.css';
const tech=[{node:<SiPython/>,title:'Python'},{node:<SiCplusplus/>,title:'C++'},{node:<SiJavascript/>,title:'JavaScript'},{node:<SiReact/>,title:'React'},{node:<SiNodedotjs/>,title:'Node.js'},{node:<SiFlask/>,title:'Flask'},{node:<SiPandas/>,title:'Pandas'},{node:<SiNumpy/>,title:'NumPy'},{node:<SiScikitlearn/>,title:'Scikit-learn'},{node:<SiPlotly/>,title:'Plotly'},{node:<SiAmazonwebservices/>,title:'AWS'},{node:<SiGit/>,title:'Git'},{node:<SiMysql/>,title:'SQL'}];
const projects=[['01','Real Estate ML Application','An end-to-end ML product for property price prediction, feature engineering, model comparison and recommendation.','ML / PYTHON / STREAMLIT / AWS'],['02','India Data Visualization','An interactive data experience for exploring 120+ demographic and socioeconomic indicators across India.','DATA / PLOTLY / STREAMLIT'],['03','NLP Application Suite','A collection of natural-language tools built around useful NLP workflows and clean interfaces.','NLP / PYTHON / AI'],['04','Career Assistant','Personalized career roadmaps, salary insights and AI-assisted learning discovery in one focused product.','REACT / TYPESCRIPT / AI']];
function App(){const[menu,setMenu]=useState(false);useEffect(()=>{const f=()=>document.documentElement.style.setProperty('--scroll',window.scrollY);addEventListener('scroll',f,{passive:true});return()=>removeEventListener('scroll',f)},[]);return <main>
<header className="nav"><a className="brand" href="#home"><b>DS</b><span>DIVYANSH SINGH</span></a><button className="menu" onClick={()=>setMenu(!menu)} aria-label="menu">{menu?'CLOSE':'MENU'}</button><div className={menu?'links open':'links'} onClick={()=>setMenu(false)}><a href="#about">ABOUT</a><a href="#work">WORK</a><a href="#stack">STACK</a><a href="#contact">CONTACT</a><a className="navGit" href="https://github.com/divbytes-prog" target="_blank">GITHUB ↗</a></div></header>
<section className="hero" id="home"><div className="aero"><AeroShards backgroundColor="#0c0910" shardColor="#896ABD" accentColor="#A855F7" placement="full" flow="stream" material="pearl" detail="balanced" effect="none" scale={1} spread={1} depth={1} speed={1} spin={1} interaction="repel" density={1.5} shardSize={1.1} stretch={1} turbulence={1} glow={1} edgeSoftness={2} bloom={0.5} grain={0.05} chromaticAberration={0.0075} transitionDuration={1} interactionRadius={1.5} interactionStrength={0.5} rippleIntensity={1} holdToGather/></div><div className="heroShade"/>
<div className="heroInner"><div className="eyebrow"><span>AVAILABLE FOR INTERNSHIPS</span><span>JAIPUR, INDIA · 26.9°N</span></div><h1><span>DIVYANSH</span><em>SINGH</em></h1><div className="heroBottom"><p>Computer Science student building at the intersection of <strong>machine learning, data and thoughtful web experiences.</strong></p><div className="heroActions"><a className="primary" href="#work">SEE SELECTED WORK <i>↘</i></a><a href="#contact">LET'S TALK <i>↗</i></a></div></div></div><div className="scrollCue">SCROLL TO EXPLORE <span>↓</span></div></section>
<section className="ticker"><LogoLoop logos={tech} speed={75} logoHeight={25} gap={55} hoverSpeed={15} scaleOnHover fadeOut fadeOutColor="#0c0910" ariaLabel="Technology stack"/></section>
<section className="about wrap" id="about"><div className="label"><span>01</span>ABOUT</div><div className="aboutLead"><p className="kicker">BUILDING SKILL THROUGH SHIPPING.</p><h2>I like turning <em>messy problems</em> into products that feel obvious.</h2></div><div className="aboutBody"><p>I'm a Computer Science student at <b>LNMIIT Jaipur</b>, exploring machine learning, data science and full-stack development through projects I can actually put in front of people.</p><p>I care about both sides of the work: the logic underneath and the experience on top. Good models matter. So do clear interfaces.</p></div><div className="metrics"><div><b>250<span>+</span></b><small>DSA PROBLEMS<br/>SOLVED</small></div><div><b>96<span>%ile</span></b><small>JEE MAIN<br/>SCORE</small></div><div><b>92<span>%</span></b><small>CLASS XII<br/>RESULT</small></div><div><b>02<span>×</span></b><small>OLYMPIAD<br/>GOLD</small></div></div></section>
<section className="work wrap" id="work"><div className="label"><span>02</span>SELECTED WORK</div><div className="sectionHead"><h2>Made with intent.<br/><em>Not just tutorials.</em></h2><a href="https://github.com/divbytes-prog" target="_blank">ALL REPOSITORIES ↗</a></div><div className="projectList">{projects.map(([n,t,d,s])=><article key={n}><div className="projectNo">{n}</div><div className="projectText"><small>{s}</small><h3>{t}</h3><p>{d}</p></div><div className="projectArrow">↗</div></article>)}</div></section>
<section className="stack wrap" id="stack"><div className="label"><span>03</span>STACK</div><div className="stackGrid"><div><p className="kicker">TOOLS CHANGE. FUNDAMENTALS STAY.</p><h2>A practical stack for <em>building & learning.</em></h2></div><div className="stackRows"><div><span>LANGUAGES</span><p>Python · C++ · Java · JavaScript · SQL</p></div><div><span>WEB</span><p>React · Node.js · Flask · Streamlit</p></div><div><span>DATA / ML</span><p>Pandas · NumPy · Scikit-learn · Plotly</p></div><div><span>TOOLS</span><p>Git · GitHub · AWS · Tableau · Jupyter</p></div></div></div></section>
<section className="education wrap"><div className="label"><span>04</span>EDUCATION</div><div className="eduCard"><div><small>2024 — 2029</small><h3>B.Tech + M.Tech<br/>Computer Science</h3></div><div><p>The LNM Institute of Information Technology</p><b>JAIPUR, RAJASTHAN</b></div><span className="eduMark">LNMIIT</span></div></section>
<section className="contact" id="contact"><div className="wrap"><div className="label"><span>05</span>CONTACT</div><p className="kicker">HAVE AN IDEA, INTERNSHIP OR COLLABORATION?</p><h2>Let’s make something<br/><em>worth remembering.</em></h2><a className="email" href="mailto:24DCS032@lnmiit.ac.in"><span>24DCS032@LNMIIT.AC.IN</span><b>↗</b></a><div className="social"><a href="https://github.com/divbytes-prog" target="_blank">GITHUB ↗</a><span>JAIPUR · INDIA</span></div></div></section>
<footer className="wrap"><span>DIVYANSH SINGH © 2026</span><span>DESIGNED & BUILT WITH CURIOSITY</span><a href="#home">BACK TO TOP ↑</a></footer></main>}createRoot(document.getElementById('root')).render(<App/>);