import React,{useEffect,useRef,useState}from'react';import{createRoot}from'react-dom/client';import AeroShards from'./AeroShards';import'./styles.css';
const projects=[
['01','Real Estate ML','Regression · Feature Engineering · Streamlit','A complete machine-learning product for property intelligence — from raw features and model comparison to a usable prediction and recommendation experience.'],
['02','India Data Atlas','Plotly · Data · Visualization','An interactive exploration layer for 120+ demographic and socioeconomic indicators, turning dense public data into a readable visual system.'],
['03','NLP Suite','NLP · Python · AI','Practical natural-language applications designed around useful workflows rather than isolated model demos.'],
['04','Career Assistant','React · TypeScript · AI','A career guidance product combining personalized roadmaps, salary context, learning discovery and an AI assistant.'],
['05','Startup Analytics','Python · Analytics · Product','Funding data transformed into an interactive analytical experience for discovering patterns, sectors and startup activity.']
];
const stages=[['01','Learn','Break the problem down until the fundamentals are clear.'],['02','Build','Turn the idea into a working system, not a slide deck.'],['03','Refine','Measure, debug, simplify and make the experience coherent.'],['04','Ship','Deploy it, put it in front of people and learn from reality.']];
function App(){const[menu,setMenu]=useState(false);const cursor=useRef(null);useEffect(()=>{const els=[...document.querySelectorAll('.reveal,.stageGrid article,.projectRail article,.numbers div')];const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('seen')}),{threshold:.12});els.forEach(e=>io.observe(e));const move=e=>{document.documentElement.style.setProperty('--mx',e.clientX+'px');document.documentElement.style.setProperty('--my',e.clientY+'px');if(cursor.current)cursor.current.style.transform=`translate3d(${e.clientX}px,${e.clientY}px,0)`};const scroll=()=>document.documentElement.style.setProperty('--sy',scrollY);addEventListener('pointermove',move,{passive:true});addEventListener('scroll',scroll,{passive:true});return()=>{io.disconnect();removeEventListener('pointermove',move);removeEventListener('scroll',scroll)}},[]);return <main><div ref={cursor} className="cursorDot"/>
<nav className="nav"><a className="wordmark" href="#top">DIVYANSH <b>SINGH</b></a><div className={menu?'navlinks open':'navlinks'} onClick={()=>setMenu(false)}><a href="#core">Core</a><a href="#work">Work</a><a href="#profile">Profile</a><a href="#contact">Contact</a><a className="navArrow" href="https://github.com/divbytes-prog" target="_blank">↗</a></div><button onClick={()=>setMenu(!menu)}>{menu?'CLOSE':'MENU'}</button></nav>
<section className="hero" id="top"><div className="heroFx"><AeroShards backgroundColor="#f6f3ee" shardColor="#b7a99a" accentColor="#8b6f5c" placement="full" flow="stream" material="pearl" detail="balanced" scale={1} spread={1.2} depth={1} speed={0.35} spin={0.5} interaction="repel" density={.7} shardSize={.75} turbulence={.6} glow={.25} edgeSoftness={2} bloom={.15} grain={.04} interactionRadius={1.2} interactionStrength={.25} rippleIntensity={.35}/></div><div className="heroVeil"/><div className="heroContent"><div className="heroTopline reveal"><span>COMPUTER SCIENCE + ML</span><span>LNMIIT · JAIPUR</span></div><h1 className="heroType"><span>I build useful</span><em>things.</em></h1><div className="heroLower reveal"><p>Software, machine learning and data experiences engineered from first principles.</p><a href="#core">Explore The Core <b>↓</b></a></div></div></section>
<section className="manifesto"><div className="manifestoTrack"><div className="marquee"><span>Good work takes patience.</span><span>Good work takes patience.</span><span>Good work takes patience.</span><span>Good work takes patience.</span></div></div><div className="manifestoCopy reveal"><p>I turn the chaotic ocean of concepts, datasets and code into <b>clear, useful systems</b> that can survive outside a notebook.</p><small>MANIFESTO / 2026</small></div></section>
<section className="core" id="core"><div className="sectionTag">01 / SYSTEM ARCHITECTURE</div><div className="coreTitle reveal"><h2>The Builder<br/><i>Loop.</i></h2><p>My process is deliberately simple. Understand deeply, build quickly, refine relentlessly, then ship.</p></div><div className="stageGrid">{stages.map(([n,t,d])=><article key={n}><div><span>{n}</span><b>{t}</b></div><p>{d}</p><i>+</i></article>)}</div><div className="systemDiagram"><div className="axis">INPUT</div><div className="node active"><span>01</span>QUESTION</div><div className="line"/><div className="node"><span>02</span>CODE</div><div className="line"/><div className="node"><span>03</span>SYSTEM</div><div className="line"/><div className="node"><span>04</span>PRODUCT</div><div className="axis">OUTPUT</div></div></section>
<section className="capabilities" id="work"><div className="sectionTag">02 / SYSTEM CAPABILITIES</div><div className="capHead reveal"><h2>Engineered to<br/><i>Learn & Ship.</i></h2><p>Selected work across machine learning, analytics and product engineering.</p></div><div className="projectRail">{projects.map(([n,t,tags,d])=><article key={n}><div className="projectTop"><span>{n}</span><small>{tags}</small></div><div className="projectBody"><h3>{t}</h3><p>{d}</p></div><div className="projectFoot"><span>EXPLORE</span><b>↗</b></div></article>)}</div></section>
<section className="profile" id="profile"><div className="sectionTag">03 / OPERATING PROFILE</div><div className="profileGrid reveal"><div className="profileIntro"><h2>Built on<br/><i>fundamentals.</i></h2><p>B.Tech + M.Tech Computer Science at LNMIIT. I work across algorithms, ML, data and web engineering — with a bias toward making things tangible.</p></div><div className="numbers"><div><strong>250+</strong><span>DSA PROBLEMS</span></div><div><strong>96</strong><span>JEE MAIN %ILE</span></div><div><strong>92%</strong><span>CLASS XII</span></div><div><strong>2×</strong><span>OLYMPIAD GOLD</span></div></div></div><div className="stackStrip"><span>PYTHON</span><span>C++</span><span>JAVA</span><span>JAVASCRIPT</span><span>REACT</span><span>NODE.JS</span><span>SQL</span><span>PANDAS</span><span>NUMPY</span><span>SCIKIT-LEARN</span><span>AWS</span></div></section>
<section className="cta" id="contact"><div className="ctaGlow"/><div className="sectionTag">BRING THE PROBLEM.</div><h2 className="reveal">Let’s <i>make it real.</i></h2><p>Internships, research, collaborations or an interesting problem that deserves a working solution.</p><a href="mailto:24DCS032@lnmiit.ac.in">Start a conversation <b>↗</b></a></section>
<footer><div className="footerBrand"><b>DS</b><div><span>DIVYANSH SINGH</span><small>COMPUTER SCIENCE · MACHINE LEARNING</small></div></div><div className="footerNav"><a href="#core">Core</a><a href="#work">Work</a><a href="https://github.com/divbytes-prog" target="_blank">GitHub ↗</a></div><div className="footerEnd"><span>JAIPUR, INDIA</span><span>© 2026</span></div></footer>
</main>}createRoot(document.getElementById('root')).render(<App/>);